apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
	matchLabels:
  	app: backend
  template:
	metadata:
  	labels:
    	app: backend
	spec:
  	containers:
			- name: backend-gateway
				image: backend-gateway
				ports:
					containerPort: 8081
			- name: backend-service1
				image: backend-service1
				ports:
					containerPort: 8083
			- name: backend-service2
				image: backend-service2
				ports:
					containerPort: 8085